### PR TITLE
Added missing items

### PR DESCRIPTION
**Pull request by dylanratcliffe**
Added some skills that I think were missing.

* [ ] @dylanratcliffe needs to add these to Trello and map to Job levels

### CODE REVIEW

**Comment by dylanratcliffe** [comment]
@igalic Requesting review

**Review by igalic — APPROVED** [review]
Looking good!

**Comment by igalic** [comment]
in 2961b110d538959149e93d1985e42c108b156e19 i've now also adapted the title of the file you renamed.

**Comment by dylanratcliffe** [comment]
Ahh good catch

**Pull request merged**
